credentials:
  usernames:
    admin:
      name: Admin User
      password: '$2b$12$sDlT8iH1KhZW7WPLz4aEiuf.gEr8kkKoz2Lt3GJ9ptMMIydzNDJnu'  # Password: admin123

cookie:
  name: momly_cookie
  key: abcdefgh12345678
  expiry_days: 3

preauthorized:
  emails:
    - admin@example.com
